create database customare_behaviour;
use customare_behaviour;
select * from customer limit 20;

# 1. What is the total revenue generated by Male and Female Customer 
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

# 2. Which customer used discount but spent more that avearge
select customer_id, sum(purchase_amount) as revenue
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount)from customer)
group by customer_id;

# 3. Which are top 5 products with the average review rating?
select item_purchased, avg(review_rating) as "Average Product Rating"
from customer group by item_purchased order by avg (review_rating) desc
limit 5;

# 4. Compare the average purchase amounts between standerd and express shipping
select shipping_type,
avg(purchase_amount)
from customer 
where shipping_type in ('standard', 'express')
group by shipping_type;

# 5. Do subsribed Customer Spend more? Compre average spend and total revenue between subscriber and non-subscribers 
select subscription_status, 
count(customer_id) as total_customers,
avg(purchase_amount) as avg_spend, 
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

# 6. Which 5 products have the highest persentage of purchases with discount applied ?
select item_purchased,
sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) * 100 as discount_rate
from customer
group by item_purchased
order  by discount_rate desc
limit 5;

# 7. segment customers into new, returning, and loyal based on their total number of previous purchases, and show the count of each segment
WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)
SELECT customer_segment,
       COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

# 8. What are the top 3 most purchased products within each category?
WITH item_count AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_count
WHERE item_rank <= 3;

# 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

# 10. What is the revenue cotribution of each age group?
select age_group,
sum(purchase_amount)as total_revenue
from customer
group by age_group
order by total_revenue desc;